### ISSUE TITLE
filter-aware-metadata/continuous-variable is returning extra `value: null` in `binRanges.*` 

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/veupathUtils#13]
The `value` prop is not in the spec and looks uniformly null.
Working around in the client for now.
Might be an EdaDataService or veupathUtils issue?
I found where the dirty work is done ;-) but it's delegated to R
https://github.com/VEuPathDB/EdaDataService/blob/master/src/main/java/org/veupathdb/service/eda/ds/plugin/filteredmetadata/ContinuousVariablePlugin.java#L98 

```
{
	"equalInterval": [
		{
			"binEnd": "358.2",
			"binStart": "17",
			"value": null,
			"binLabel": "[17, 358.2]"
		},
		{
			"binEnd": "699.4",
			"binStart": "358.2",
			"value": null,
			"binLabel": "(358.2, 699.4]"
		},
		{
			"binEnd": "1040.6",
			"binStart": "699.4",
			"value": null,
			"binLabel": "(699.4, 1041]"
		},
		{
			"binEnd": "1381.8",
			"binStart": "1040.6",
			"value": null,
			"binLabel": "(1041, 1382]"
		},
// SNIPPED		
	]
}
```

**Comment by d-callan** [comment]
fixed v2.2.3
