### ISSUE TITLE
Backend: Optionally impute 0s for numeric terms.

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/veupathUtils#3]
The use case we have currently is for mbio, discussed in slack #eda-backend. from that conversation @steve-fischer-200 said " i just have to do an initial query to see if any samples in my subset have a value for this variable.  if so, then fill in zeros".

There are variables that represent abundance values that we would like to automatically impute 0 values for when they are requested for vizs. **We may still require some discussion**, particularly around whether we also want this behavior in the subset tab histos.

**Comment by asizemore** [comment]
Nothing for outreach to QA
