### ISSUE TITLE
Remove dependency on microbenchmark

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/veupathUtils#52]
We don't need this anymore. We tried to use this package for speed testing a few years ago but we didn't maintain it. Not worth keeping around at this point.

**Comment by bobular** [comment]
I was going to tackle this but I'm not going to remove this without further discussion. It's used in one place in test-class-Megastudy.R:

```
  ## minimal use case, with real vocabularies. based on a heavily subsetted megastudy.
  megastudyReal <- Megastudy(
    data=megastudyDataReal,
    ancestorIdColumns=c(
      'EUPATH_0000605.Study_stable_id', 
      'GAZ_00000448.GeographicLocation_stable_id',
      'OBI_0000659.ParentOfSample_stable_id',
      'EUPATH_0000609.Sample_stable_id'
    ),
    studySpecificVocabularies=studyVocabsReal
  )

  benchmark <- microbenchmark::microbenchmark(getDTWithImputedZeroes(megastudyReal, megastudyVariablesReal, verbose = FALSE))
  print(benchmark)
  expect_true(mean(benchmark$time)/1000000 < 55) ## this is in milliseconds
  expect_true(median(benchmark$time)/1000000 < 55)
```

**Comment by asizemore** [comment]
ooooooooh and the megastudy no less. That's dangerous territory. Let's not worry about removing the dependency.

Thanks for looking into it!

**Comment by asizemore** [comment]
> So should we add it to the dependencies of Rserve/R-local-dev?

Yes, let's do that. Happy if it just gets added to a PR, or we can make a new issue.
